trigger:
  - main

pool: AJPOOL

stages:
  - stage: Terraform_Init_Plan
    jobs:
      - job: Terraform_init
        steps:
        
        - task: SonarQubePrepare@8
          displayName: SonarScan
          condition: eq(variables['Build.SourceBranchName'], 'main')
          inputs:
            SonarQube: 'Sonar-SVC-Connect'
            scannerMode: 'cli'
            configMode: 'manual'
            cliProjectKey: 'AJ-DEVSECOPS_TerraformInfra.git_b3b596d6-767b-4a9d-b407-f2b565ccca22'
            cliSources: '$(System.DefaultWorkingDirectory)/Dev'
            extraProperties: 
        

        - task: SonarQubeAnalyze@8
          condition: eq(variables['Build.SourceBranchName'], 'main')
          inputs:
            jdkversion: 'JAVA_HOME_17_X64'
        
        - task: SonarQubePublish@8
          condition: eq(variables['Build.SourceBranchName'], 'main')
          inputs:
            pollingTimeoutSec: '300'

        - task: TerraformInstaller@1
          displayName: Terraform_Install
          inputs:
            terraformVersion: 'latest'
        
        - task: TerraformTask@5
          displayName: Terraform_Init
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Dev'
            backendServiceArm: 'Terraform-SVC'
            backendAzureRmStorageAccountName: 'ajstg'
            backendAzureRmContainerName: 'brucecontainer'
            backendAzureRmKey: 'terraform.tfstate'

        - task: TerraformTask@5
          displayName: Terraform_Plan
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Dev'
            environmentServiceNameAzureRM: 'Terraform-SVC'
        


  - stage: Manual_Validation
    pool: server
    jobs:
      - job: Manual_Validation
        steps:
        - task: ManualValidation@1
          inputs:
            notifyUsers: 'arjun@hshasharma89gmail.onmicrosoft.com'
            approvers: 'arjun@hshasharma89gmail.onmicrosoft.com'

  - stage: Terraform_Apply
    jobs:
      - job: Terraform_Apply
        steps:
        - task: TerraformTask@5
          displayName: Terraform_Init
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Dev'
            backendServiceArm: 'Terraform-SVC'
            backendAzureRmStorageAccountName: 'ajstg'
            backendAzureRmContainerName: 'brucecontainer'
            backendAzureRmKey: 'terraform.tfstate'

        - task: TerraformTask@5
          displayName: Terraform_Apply
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Dev'
            environmentServiceNameAzureRM: 'Terraform-SVC'